"""empty message

Revision ID: 079f9eea942d
Revises: 435a296fd954
Create Date: 2025-12-15 14:04:29.737127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079f9eea942d'
down_revision = '435a296fd954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.alter_column('is_activated',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('student_attendance_record', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance_record', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.alter_column('is_activated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
