"""empty message

Revision ID: c25cd954a244
Revises: 079f9eea942d
Create Date: 2025-12-15 14:19:05.301403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25cd954a244'
down_revision = '079f9eea942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.alter_column('attendance_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_class_session_attendance_code'), ['attendance_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_session_attendance_code'))
        batch_op.alter_column('attendance_code',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
